Update 6.5.4
AnacondaRecipes/nbconvert-feedstock pull request #11
Opened 2022-11-03 22:57 UTC by Jrice1317

- Updated version and hash
- Alphabetized run section
- Updated pinnings
- Added install_reqs
- Updated urls
- Added license and doc_source urls

Jira: https://anaconda.atlassian.net/browse/PKG-155
https://github.com/jupyter/nbconvert/tree/main

2022-11-03 22:57 UTC, anaconda-pkg-build commented
Linter check failed, with the following output:
The following problems have been found:

ERROR: /tmp/abs_c0jdq5se57/clone/recipe/meta.yaml:74: invalid_url: https://github.com/jupyter/nbconvert/tree/6.5.4/docs : Not reachable: 404
ERROR: /tmp/abs_c0jdq5se57/clone/recipe/meta.yaml:82: invalid_url: https://github.com/jupyter/nbconvert/tree/6.5.4/docs : Not reachable: 404
Errors were found

2022-11-08 21:39 UTC, varlackc approved these changes
LGTM

2022-11-08 21:58 UTC, ELundby45 approved these changes
LGTM. I'll just add a reminder to remove the abs.yaml before deploying.

2022-11-09 06:41 UTC, katietz requested changes

2022-11-09 06:41 UTC, katietz commented on abs.yaml
> +channels:
please remove this channel stuff

2022-11-09 06:41 UTC, katietz commented on recipe/meta.yaml
> +  license_url: https://github.com/jupyter/nbconvert/blob/6.5.3/LICENSE
there is a license_file in package.  No need for the license_url.  It is superflous, even problematic mid/long term

2022-11-09 06:41 UTC, katietz commented on recipe/meta.yaml
> +  doc_source_url: https://github.com/jupyter/nbconvert/tree/6.5.3/docs
doc_source_url is superflous.  there is already a doc_url

2022-11-11 12:07 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_63376jusrw/clone/recipe/meta.yaml:80: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_63376jusrw/clone/recipe/meta.yaml:80: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-11 12:10 UTC, katietz commented
please upload first tinycss2 before building this package!

2022-11-11 12:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_94dq16kbz0/clone/recipe/meta.yaml:80: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_94dq16kbz0/clone/recipe/meta.yaml:80: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-11 12:27 UTC, katietz commented
after uploading its dependencies, it can be build without private channel information abs.yaml, as you see now

2022-11-11 12:30 UTC, katietz approved these changes
after all issues are resolved, final build was successful without private channel, the PR is ready for approval. and it looks good to me now.

2022-11-11 12:30 UTC, katietz commented on recipe/meta.yaml
> +  doc_source_url: https://github.com/jupyter/nbconvert/tree/6.5.3/docs
done it for you.  Next time please adjust before asking me for a second review

2022-11-11 12:30 UTC, katietz commented on recipe/meta.yaml
> +  license_url: https://github.com/jupyter/nbconvert/blob/6.5.3/LICENSE
done for you ...

2022-11-11 12:30 UTC, katietz commented on abs.yaml
> +channels:
done for you

2022-11-11 14:22 UTC, skupr-anaconda approved these changes

2022-11-14 18:15 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_b7avjqg_ie/clone/recipe/meta.yaml:80: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_b7avjqg_ie/clone/recipe/meta.yaml:80: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-14 18:29 UTC, merged

2022-11-14 18:31 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_8fbv1sd7kt/clone/recipe/meta.yaml:80: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_8fbv1sd7kt/clone/recipe/meta.yaml:80: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>